#!/bin/bash
set -e

##############################################################################################
#                                                                                            #
# Yapımcı: Ömer ŞERAN                                                                        #
# Website: larkpanel.org - omersrn.com                                                       #
#                                                                                            #
# Eğer bunları okuyorsan helal, şifreyi kırmayı başarmışsın,                                 #
# Fakat insanların emeği ile oynamak haramdır bunu unutma,                                   #
# Eğer şifresiz bir şekilde emeklermizi paylaşırsan hakkımıza girersin,                      #
# Sadece kodlara bakmaya gelenlere lafım yoktur, ismimi silip paylaşanlara haram olsun.      #
# Haydi şimdi iyi günler sana, yukarıda yazdıklarımı iyi okuduğuna emin ol tamam mı?         #
#                                                                                            #
##############################################################################################

surum="1.0.0"
down="download.larkpanel.org"

ana_sifirla(){
clear
sleep 0.1
echo -e "\033[1;31mDİKKAT: \033[1;33mBu işlem bütün iptables ayarlarınızı sıfırlayacak ve scriptin kurduğu her şeyi kaldıracak.\033[0m"
read -p "Emin misin? (E/h) " RESP
if [ "$RESP" = "E" ]; then
echo -e "\033[1;33mSıfırlama işlemi başlatıldı.\033[0m"
nohup ipset --flush >/dev/null 2>&1 
nohup yum remove ipset -y >/dev/null 2>&1 
nohup iptables --flush >/dev/null 2>&1 
echo -e "\033[1;32mSıfırlama işlemi başarıyla tamamlandı, scriptin kurduğu her şey kaldırıldı.\033[0m"
else
echo -e "\033[1;33mİşlem iptal edilmiştir.\033[0m"
fi


}

ana_proxy(){
clear
echo -e "\033[1;33mGüncel proxy listesi indiriliyor...\033[0m"
aaa=$(wget http://$down/ssh/mc/toplam.php -q -O -)
cd /usr/local/src
rm -rf proxy.sh
rm -rf proxies.yml
nohup wget http://$down/ssh/mc/proxy.sh >/dev/null 2>&1 
nohup wget http://$down/ssh/mc/proxies.yml >/dev/null 2>&1 
echo -e "\033[1;32mGüncel proxy listesi indirildi.\033[0m"
sleep 1
echo -e "\033[1;33mProxy adresleri engelleniyor...\033[0m"
sleep 2
echo -e "\033[1;31mDİKKAT: Bu işlem sunucunuzun hızına bağlı olup, minimum 3-10 dakika arası sürmektedir.\033[0m"
cd /usr/local/src
nohup sh proxy.sh >/dev/null 2>&1 
echo -e "\033[1;32mProxy adresleri engellendi. ($aaa)\033[0m"
rm -rf /usr/local/src/proxy.sh
rm -rf /usr/local/src/proxies.yml
}

ana_yabanci(){
clear
sleep 0.1
echo -e "\033[1;33mVeritabanı indiriliyor, lütfen bekleyin.\033[0m"
nohup sudo yum -y install ipset >/dev/null 2>&1
nohup rm -f tr.zone >/dev/null 2>&1
nohup sudo ipset destroy geoAllowIP$ulke >/dev/null 2>&1
nohup wget  http://www.ipdeny.com/ipblocks/data/countries/tr.zone >/dev/null 2>&1
nohup sudo ipset -N geoAllowIP nethash >/dev/null 2>&1
echo -e "\033[1;32mVeritabanı indirildi.\033[0m"
sleep 1
echo -e "\033[1;33mTürkiye dışı erişimler engelleniyor, lütfen bekleyin.\033[0m"
cat tr.zone | while read line
do
	nohup sudo ipset -A geoAllowIP $line >/dev/null 2>&1
done
nohup sudo ipset save geoAllowIP >/dev/null 2>&1
nohup sudo iptables -A INPUT -m state --state NEW -m set ! --set geoAllowIP src -j DROP >/dev/null 2>&1
nohup sudo iptables-save >/dev/null 2>&1
nohup sudo service iptables save >/dev/null 2>&1	 
nohup rm -f tr.zone >/dev/null 2>&1
echo -e "\033[1;32mTürkiye dışı erişimler kapatılmıştır.\033[0m"


}

ana_ulke(){
clear
echo -n -e "\033[1;36mÜlke kısaltması (Fransa -> fr): \033[0m"
read ulke
clear
echo -e "\033[1;33mLütfen bekleyin, $ulke ülkesi birazdan engellenecek.\033[0m"
cd /root/
nohup sudo yum -y install ipset >/dev/null 2>&1
rm -f $ulke.zone
nohup nohup sudo ipset destroy geoAllowIP$ulke >/dev/null 2>&1
nohup wget  http://www.ipdeny.com/ipblocks/data/countries/$ulke.zone >/dev/null 2>&1 
nohup sudo ipset -N geoAllowIP$ulke nethash >/dev/null 2>&1
cat $ulke.zone | while read line
do
	nohup sudo ipset -A geoAllowIP$ulke $line >/dev/null 2>&1
done
nohup sudo ipset save geoAllowIP$ulke >/dev/null 2>&1
nohup sudo iptables -A INPUT -m state --state NEW -m set --set geoAllowIP$ulke src -j DROP >/dev/null 2>&1
nohup sudo iptables-save >/dev/null 2>&1
nohup sudo service iptables save >/dev/null 2>&1
rm -f $ulke.zone >/dev/null 2>&1
echo -e "\033[1;32m$ulke adlı ülke başarıyla engellendi.\033[0m"


}

ana_ip(){
clear
echo -n -e "\033[1;36mIP Adresi: \033[0m"
read ip
iptables -A INPUT -s $ip -j DROP
echo -e "\033[1;32m$ip ip adresi başarıyla engellendi.\033[0m"
}

ana_menu(){

clear
	echo -e "\033[1;33m###################################################################\033[1;32m \033[0m"
	echo -e "\033[1;33m#                                                                 #\033[1;32m \033[0m"
	echo -e "\033[1;33m#                     \033[0;36mScript by \033[1;37mÖmer ŞERAN \033[0m                       \033[1;33m# \033[0m"
	echo -e "\033[1;33m#                     \033[0;36mSürüm: \033[1;37mv$surum                               \033[0m\033[1;33m# \033[0m"
	echo -e "\033[1;33m#                                                                 #\033[1;33m \033[0m"
	echo -e "\033[1;33m###################################################################\033[1;32m \033[0m"
	echo -e "\033[1;35mDUYURU: \033[1;37m$duyuru"
	echo -e "\033[1;36m1) Proxy adreslerini engelle \033[1;32m($songuncel)\033[0m"
	echo -e "\033[1;36m2) Belirli ülkeyi engelle\033[0m"
	echo -e "\033[1;36m3) Bir ip adresini engelle\033[0m"	
	echo -e "\033[1;36m4) Türkiye dışı erişimleri engelle \033[0m"	
	echo -e "\033[1;36m5) Tüm Ayarları Sıfırla \033[0m"		
	echo -e "\033[1;36m0) Çıkış\033[0m"
read secenek
 
case $secenek in
 1)
ana_proxy
 ;;
 2)
ana_ulke
 ;;
 3)
ana_ip
;; 
 4)
ana_yabanci
;;
 5)
ana_sifirla 
 ;;
 0)
 clear
 exit
 ;;
*)
echo -e "\033[1;33m###################################################################\033[1;32m \033[0m"
echo -e "\033[1;33m#                                                                 #\033[1;32m \033[0m"
echo -e "\033[1;33m#          \033[1;33mYanlış tuşlama yapıldı, script kapatılıyor.      \033[0m      \033[1;33m# \033[0m"
echo -e "\033[1;33m#                            \033[1;31mİyi günler                           \033[0m\033[1;33m# \033[0m"
echo -e "\033[1;33m#                                                                 #\033[1;33m \033[0m"
echo -e "\033[1;33m###################################################################\033[1;32m \033[0m"
exit
;;

esac

}

#--------------------------------------------------------------------------#
clear
command -v curl >/dev/null 2>&1 || error_curl="1"
if [[ $error_curl -eq 1 ]]
	then
update_sorun
fi
if curl -s --head  --request GET http://$down/ssh/mc/locked | grep "200 OK" > /dev/null; 
then
clear
echo -e "\033[1;33m###################################################################\033[1;32m \033[0m"
echo -e "\033[1;33m#                                                                 #\033[1;32m \033[0m"
echo -e "\033[1;33m#                \033[1;33mScript geçici olarak, servis dışıdır.      \033[0m      \033[1;33m# \033[0m"
echo -e "\033[1;33m#                    \033[1;37m~ \033[1;31mDaha sonra tekrar deneyin \033[1;37m~                \033[0m\033[1;33m# \033[0m"
echo -e "\033[1;33m#                                                                 #\033[1;33m \033[0m"
echo -e "\033[1;33m###################################################################\033[1;32m \033[0m"
exit
fi
echo -e "\033[1;37mScript Başlatılıyor: \033[1;31mSunucu bağlantıları kontrol ediliyor...\033[0m"
if curl -s --head  --request GET $down | grep "200 OK" > /dev/null; then
echo -e "\033[1;37mScript Başlatılıyor: \033[1;33mİndirme sunucusuna bağlantı kuruldu.\033[0m"
else
clear
echo -e "\033[1;33m###################################################################\033[1;32m \033[0m"
echo -e "\033[1;33m#                                                                 #\033[1;32m \033[0m"
echo -e "\033[1;33m#    \033[1;33mSunucuya ulaşılamadığı için, kontroller yapılamadı.    \033[0m      \033[1;33m# \033[0m"
echo -e "\033[1;33m#              \033[1;37m~ \033[1;31mDaha sonra tekrar deneyin \033[1;37m~                      \033[0m\033[1;33m# \033[0m"
echo -e "\033[1;33m#                                                                 #\033[1;33m \033[0m"
echo -e "\033[1;33m###################################################################\033[1;32m \033[0m"
exit
fi
if curl -s --head  --request GET http://$down/ssh/mc/v$surum | grep "200 OK" > /dev/null; then
echo -e "\033[1;37mScript Başlatılıyor: \033[1;33mYeni bir güncelleme bulunamadı.\033[0m"
else
echo -e "\033[1;37mScript Başlatılıyor: \033[1;33mYeni versiyon bulundu, script güncelleniyor...\033[0m"
cd /root
nohup wget http://$down/ssh/mc/update/yenisurum.tar.bz2 >/dev/null 2>&1
nohup tar xvjf yenisurum.tar.bz2 >/dev/null 2>&1
cd /root
rm -rf mcbot
nohup mv mcbot-yenisurum mcbot >/dev/null 2>&1
rm -rf yenisurum.tar.bz2
echo -e "\033[1;37mScript Başlatılıyor: \033[1;33mScript başarıyla güncellendi. Güncellemeye rağmen açılmazsa site üzerinden indirin.\033[0m"
exit
fi
duyuru=$(wget http://$down/ssh/mc/duyuru.php -q -O -)
songuncel=$(wget http://$down/ssh/mc/guncel.php -q -O -)
ana_menu